### ISSUE TITLE
Hyperlinks don't open

### ISSUE THREAD

**Issue by remib** [drrasic/ionic_twitter_feed#2]
Great solution but I notice you don't actually create a working hyperlink in your filter.

I've managed to implement hyperlinks using href but seeing as this is for ionic it needs to open using the inappbrowser plugin, otherwise the link opens in the same webview as the app and there's no way to return to the app without closing it and reopening it. I've tried implementing this via the suggested window.open method in the plugin docs but the ng-click gets removed at some stage, presumably because of unsafe html and/or scopes but I cannot figure out a solution.

Any ideas how to get clickable links within tweets that open in inappbrowser?

Many thanks.

**Comment by drrasic** [comment]
Yeah i had the same problem, if i remember corectly that kind of stuff doesnt work because ofthe linking processes in angular Compiler, so i think that can be done with a directive so you can go that route, ill probably try to do that when i snatch some spare time  to improve this plugin..

**for my client i just opened whole tweet in innap browser when user "ng-clicked" anywhere on the post. and it was ok with him ;)

**Comment by remib** [comment]
That might actually suffice for now, thanks for getting back to me.

Edit: I did come across this which might help http://plnkr.co/edit/vUWro6?p=preview it compiles the tweet correctly but I haven't quite got my head around it yet!

**Comment by drrasic** [comment]
Yeah thats it, i have updated plugin with that solution.
